correct update from unpackaged
since https://github.com/greenplum-db/gpdb/commit/ecc2f0b2b7a11ab137078db3383d7245771df21a
postgis does not correct update from unpackaged because it first do
`create or replace objects` and second do `alter extension add`
causing follow errors
```sql
create extension postgis;
ERROR:  PostGIS is already installed in schema 'public'

create extension postgis from unpackaged;
ERROR:  function _postgis_deprecate(text,text,text) is not a member of extension "postgis"
DETAIL:  An extension is not allowed to replace an object that it does not own.
```
solution consists in first do `alter extension add` and second do
`create or replace objects`